export let properties = [
  {
    project_name: "Lodha Splendora",
    location: "Ghodbunder Road, Thane",
    price: 7500000,
    bhk: "2 BHK",
    possession: "Dec 2025",
    amenities: ["Swimming Pool", "Gym", "Garden", "Clubhouse"],
    highlights: "Highway touch property near D-Mart",
    images: [
      "http://localhost:8081/images/property_1.avif",
      "http://localhost:8081/images/property_2.avif",
    ],
    brochure: "http://localhost:8081/images/splendora_brochure.pdf",
    floorplan: "http://localhost:8081/images/splendora_floorplan.png",
  },

  {
    project_name: "Hiranandani Estate",
    location: "Patlipada, Thane",
    price: 9500000,
    bhk: "3 BHK",
    possession: "Ready to Move",
    amenities: ["Park", "Clubhouse", "Sports Court"],
    highlights: "Premium township with luxury lifestyle",
    images: [
      "http://localhost:8081/images/property_1.avif",
      "http://localhost:8081/images/property_3.avif",
    ],
    brochure: "http://localhost:8081/images/splendora_brochure.pdf",
    floorplan: "http://localhost:8081/images/splendora_floorplan.png",
  },

  {
    project_name: "Rustomjee Urbania",
    location: "Majiwada, Thane",
    price: 8200000,
    bhk: "2 BHK",
    possession: "June 2026",
    amenities: ["Swimming Pool", "Cricket Turf", "Kids Play Area"],
    highlights: "Close to Viviana Mall and Jupiter Hospital",
    images: [
      "http://localhost:8081/images/property_1.avif",
      "http://localhost:8081/images/property_3.avif",
    ],
    brochure: "http://localhost:8081/images/splendora_brochure.pdf",
    floorplan: "http://localhost:8081/images/splendora_floorplan.png",
  },

  {
    project_name: "Piramal Vaikunth",
    location: "Balkum, Thane",
    price: 6900000,
    bhk: "1 BHK",
    possession: "Dec 2024",
    amenities: ["Temple Garden", "Indoor Games", "Yoga Deck"],
    highlights: "Spread over 32 acres with green views",
    images: [
      "http://localhost:8081/images/property_1.avif",
      "http://localhost:8081/images/property_2.avif",
    ],
    brochure: "http://localhost:8081/images/splendora_brochure.pdf",
    floorplan: "http://localhost:8081/images/splendora_floorplan.png",
  },

  {
    project_name: "Tata Serein",
    location: "Pokhran Road 2, Thane",
    price: 12000000,
    bhk: "3 BHK",
    possession: "Sep 2026",
    amenities: ["Gym", "Spa", "Yoga Center", "Meditation Area"],
    highlights: "Nature-inspired luxury living with forest views",
    images: [
      "http://localhost:8081/images/property_1.avif",
      "http://localhost:8081/images/property_3.avif",
    ],
    brochure: "http://localhost:8081/images/splendora_brochure.pdf",
    floorplan: "http://localhost:8081/images/splendora_floorplan.png",
  },
];


const DUMMY_PROPERTIES = [
  {
    _id: "1",
    project_name: "Lodha Splendora",
    location: "Ghodbunder Road, Thane",
    price: 7500000,
    bhk: "2 BHK",
    possession: "Dec 2025",
    highlights: "Highway touch property near D-Mart",
    amenities: ["Swimming Pool", "Gym", "Garden", "Security"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    ],
    status: "active",
    views: 245,
    inquiries: 12,
    created_at: "2024-01-15",
  },
  {
    _id: "2",
    project_name: "Oberoi Sky City",
    location: "Borivali East, Mumbai",
    price: 12000000,
    bhk: "3 BHK",
    possession: "Ready to Move",
    highlights: "Luxury apartments with modern amenities",
    amenities: ["Clubhouse", "Swimming Pool", "Gym", "Parking", "Security"],
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    status: "active",
    views: 432,
    inquiries: 28,
    created_at: "2024-01-10",
  },
  {
    _id: "3",
    project_name: "Godrej Properties",
    location: "Vikhroli, Mumbai",
    price: 9500000,
    bhk: "2 BHK",
    possession: "Mar 2026",
    highlights: "Green living with eco-friendly design",
    amenities: ["Garden", "Yoga Deck", "Gym", "Security", "Power Backup"],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    status: "active",
    views: 189,
    inquiries: 8,
    created_at: "2024-02-01",
  },
  {
    _id: "4",
    project_name: "Hiranandani Fortune City",
    location: "Panvel, Navi Mumbai",
    price: 5500000,
    bhk: "1 BHK",
    possession: "Ready to Move",
    highlights: "Affordable housing near metro station",
    amenities: ["Swimming Pool", "Gym", "Security"],
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    ],
    status: "sold",
    views: 567,
    inquiries: 45,
    created_at: "2023-12-20",
  },
  {
    _id: "5",
    project_name: "Runwal Gardens",
    location: "Dombivli, Thane",
    price: 6800000,
    bhk: "2 BHK",
    possession: "June 2025",
    highlights: "Spacious apartments with great connectivity",
    amenities: ["Garden", "Clubhouse", "Kids Play Area", "Security"],
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
    ],
    status: "active",
    views: 312,
    inquiries: 19,
    created_at: "2024-01-25",
  },
  {
    _id: "6",
    project_name: "Shapoorji Pallonji",
    location: "Kandivali West, Mumbai",
    price: 15000000,
    bhk: "4 BHK",
    possession: "Dec 2024",
    highlights: "Premium luxury with panoramic city views",
    amenities: [
      "Swimming Pool",
      "Spa",
      "Gym",
      "Clubhouse",
      "Valet Parking",
      "Security",
    ],
    images: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    ],
    status: "active",
    views: 678,
    inquiries: 52,
    created_at: "2024-02-05",
  },
];