// src/pages/mockData.js
// Central mock data store for the entire CRM system

export const bhkOptions = [
  "Studio",
  "1 BHK",
  "2 BHK",
  "3 BHK",
  "4 BHK",
  "5 BHK",
  "Duplex",
  "Simplex",
];

/* ─── PLANS ──────────────────────────────────────────────────────────────────── */
export const PLAN_CONFIG = {
  BASIC: {
    color: "from-gray-400 to-gray-600",
    badge: "bg-gray-100 text-gray-700",
    features: [
      "100 Leads/month",
      "Property Management",
      "Lead Management",
      "Site Visit Tracking",
      "Basic Dashboard",
      "Limited Broadcasting",
    ],
    limits: {
      leads: 100,
      export: false,
      calendar: false,
      filters: false,
      broadcasting: "limited",
    },
  },
  PRO: {
    color: "from-blue-500 to-indigo-600",
    badge: "bg-blue-100 text-blue-700",
    features: [
      "Unlimited Leads",
      "Calendar View",
      "Task & Follow-up",
      "Lead Filters",
      "Segmented Broadcasting",
      "Property Analytics",
      "Lead Aging",
      "CSV Export",
    ],
    limits: {
      leads: Infinity,
      export: true,
      calendar: true,
      filters: true,
      broadcasting: "segmented",
    },
  },
  ENTERPRISE: {
    color: "from-amber-400 to-orange-500",
    badge: "bg-amber-100 text-amber-700",
    features: [
      "Everything in Pro",
      "Custom Branding",
      "API Integrations",
      "Priority Support",
    ],
    limits: {
      leads: Infinity,
      export: true,
      calendar: true,
      filters: true,
      broadcasting: "full",
    },
  },
};

/* ─── LEAD STAGES ────────────────────────────────────────────────────────────── */
// Replace existing LEAD_STAGES with this
export const LEAD_STAGES = [
  "New",
  "Suspect",
  "Prospect",
  "Negotiation",
  "Closed",
  "Lost",
  "On Hold",
];

// Replace existing STAGE_COLORS with this
export const STAGE_COLORS = {
  New: { bg: "bg-blue-100", text: "text-blue-700" },
  Suspect: { bg: "bg-purple-100", text: "text-purple-700" },
  Prospect: { bg: "bg-indigo-100", text: "text-indigo-700" },
  Negotiation: { bg: "bg-amber-100", text: "text-amber-700" },
  Closed: { bg: "bg-emerald-100", text: "text-emerald-700" },
  Lost: { bg: "bg-red-100", text: "text-red-600" },
  "On Hold": { bg: "bg-gray-100", text: "text-gray-500" },
};

// ✅ NEW — Call Feedback options + colors
export const CALL_FEEDBACK_OPTIONS = [
  "Assign",           // ✅ first stage
  "Interested",
  "Not Interested",
  "No Response",
  "Call Later",
  "Visit Scheduled",
  "Invalid Number",
];

export const CALL_FEEDBACK_COLORS = {
  "Assign":          { bg: "bg-violet-100",  text: "text-violet-700"  }, // ✅ added
  "Interested":      { bg: "bg-emerald-100", text: "text-emerald-700" },
  "Not Interested":  { bg: "bg-red-100",     text: "text-red-600"     },
  "No Response":     { bg: "bg-gray-100",    text: "text-gray-500"    },
  "Call Later":      { bg: "bg-amber-100",   text: "text-amber-700"   },
  "Visit Scheduled": { bg: "bg-blue-100",    text: "text-blue-700"    },
  "Invalid Number":  { bg: "bg-orange-100",  text: "text-orange-700"  },
};
export const LEAD_SOURCES = [
  "Chatbot",
  "Website",
  "Manual",
  "Broadcast",
  "Import",
];

export const VISIT_STATUSES = [
  "Scheduled",
  "Completed",
  "Cancelled",
  "No Show",
  "Interested",
  "Not Interested",
];

/* ─── PROPERTIES ─────────────────────────────────────────────────────────────── */
export const MOCK_PROPERTIES = [
  {
    id: 1,
    name: "Skyline Apartments Block A",
    location: "Sector 62, Noida",
    price: 4500000,
    type: "Apartment",
    leads: 42,
    visits: 18,
    closed: 3,
  },
  {
    id: 2,
    name: "Green Valley Villas",
    location: "Sector 150, Noida",
    price: 9500000,
    type: "Villa",
    leads: 28,
    visits: 12,
    closed: 2,
  },
  {
    id: 3,
    name: "Metro Heights 2BHK",
    location: "Sector 78, Noida",
    price: 3200000,
    type: "Apartment",
    leads: 61,
    visits: 24,
    closed: 5,
  },
  {
    id: 4,
    name: "Central Park Plots",
    location: "Sector 47, Noida",
    price: 7800000,
    type: "Plot",
    leads: 19,
    visits: 8,
    closed: 1,
  },
];

/* ─── LEADS ──────────────────────────────────────────────────────────────────── */
// notes is now an array of { text, date } — newest first.
// Append-only: new notes are unshifted to the front on save.
export const MOCK_LEADS = [
  {
    id: 1,
    name: "Rahul Verma",
    phone: "9876543210",
    email: "rahul@email.com",
    property: "Skyline Apartments Block A",
    propertyId: 1,
    budget: 5000000,
    location: "Noida",
    stage: "New",
    source: "Chatbot",
    assignedTo: "Vikram Singh",
    notes: [
      { text: "Very interested, called twice", date: "2025-02-14" },
      {
        text: "Initial inquiry via chatbot, no email provided",
        date: "2025-02-10",
      },
    ],
    followUpDate: "2025-02-20",
    visitDate: null,
    createdAt: "2025-02-10",
    updatedAt: "2025-02-14",
    timeline: [
      {
        action: "Lead Created",
        date: "2025-02-10",
        note: "Via chatbot inquiry",
      },
      {
        action: "Contacted",
        date: "2025-02-12",
        note: "Called and discussed project",
      },
    ],
  },
  {
    id: 2,
    name: "Sneha Gupta",
    phone: "9811223344",
    email: "sneha@email.com",
    property: "Green Valley Villas",
    propertyId: 2,
    budget: 10000000,
    location: "Noida",
    stage: "Visit Scheduled",
    source: "Website",
    assignedTo: "Priya Sharma",
    notes: [
      { text: "Wants 3BHK, budget flexible", date: "2025-02-15" },
      { text: "Shared brochure over WhatsApp", date: "2025-02-10" },
      { text: "Came in through website inquiry form", date: "2025-02-08" },
    ],
    followUpDate: "2025-02-18",
    visitDate: "2025-02-18",
    createdAt: "2025-02-08",
    updatedAt: "2025-02-15",
    timeline: [
      { action: "Lead Created", date: "2025-02-08", note: "Website inquiry" },
      { action: "Contacted", date: "2025-02-10", note: "Shared brochure" },
      {
        action: "Visit Scheduled",
        date: "2025-02-15",
        note: "Confirmed for 18th Feb",
      },
    ],
  },
  {
    id: 3,
    name: "Arjun Patel",
    phone: "9900112233",
    email: "",
    property: "Metro Heights 2BHK",
    propertyId: 3,
    budget: 3500000,
    location: "Delhi",
    stage: "Negotiation",
    source: "Manual",
    assignedTo: "Vikram Singh",
    notes: [
      { text: "Wants 2% discount, may accept 1%", date: "2025-02-14" },
      {
        text: "Visited site, liked the layout and ventilation",
        date: "2025-02-12",
      },
      { text: "Walk-in customer, interested in 2BHK only", date: "2025-02-05" },
    ],
    followUpDate: "2025-02-16",
    visitDate: "2025-02-12",
    createdAt: "2025-02-05",
    updatedAt: "2025-02-14",
    timeline: [
      { action: "Lead Created", date: "2025-02-05", note: "Walk-in customer" },
      { action: "Contacted", date: "2025-02-06", note: "In-person meeting" },
      {
        action: "Visit Scheduled",
        date: "2025-02-08",
        note: "Site visit booked",
      },
      {
        action: "Visit Completed",
        date: "2025-02-12",
        note: "Liked the property",
      },
      { action: "Negotiation", date: "2025-02-14", note: "Asked for discount" },
    ],
  },
  {
    id: 4,
    name: "Meera Shah",
    phone: "9988776655",
    email: "meera@email.com",
    property: "Skyline Apartments Block A",
    propertyId: 1,
    budget: 4800000,
    location: "Noida",
    stage: "Closed",
    source: "Broadcast",
    assignedTo: "Priya Sharma",
    notes: [
      { text: "Deal done at 45L, booking amount received", date: "2025-02-13" },
      {
        text: "Price negotiation done, agreed on final number",
        date: "2025-02-10",
      },
      { text: "Very satisfied after site visit", date: "2025-02-05" },
    ],
    followUpDate: null,
    visitDate: "2025-02-05",
    createdAt: "2025-01-28",
    updatedAt: "2025-02-13",
    timeline: [
      {
        action: "Lead Created",
        date: "2025-01-28",
        note: "From broadcast campaign",
      },
      { action: "Contacted", date: "2025-01-30", note: "Phone call" },
      {
        action: "Visit Scheduled",
        date: "2025-02-02",
        note: "Visit confirmed",
      },
      { action: "Visit Completed", date: "2025-02-05", note: "Very satisfied" },
      { action: "Negotiation", date: "2025-02-10", note: "Price discussion" },
      {
        action: "Deal Closed",
        date: "2025-02-13",
        note: "Booking amount received",
      },
    ],
  },
  {
    id: 5,
    name: "Kavya Nair",
    phone: "9700445566",
    email: "kavya@email.com",
    property: "Central Park Plots",
    propertyId: 4,
    budget: 8000000,
    location: "Noida",
    stage: "Lost",
    source: "Website",
    assignedTo: null,
    notes: [
      { text: "Budget constraint, went with competitor", date: "2025-02-14" },
      {
        text: "Seemed hesitant after site visit, price was a concern",
        date: "2025-02-08",
      },
    ],
    followUpDate: null,
    visitDate: "2025-02-08",
    createdAt: "2025-02-01",
    updatedAt: "2025-02-14",
    timeline: [
      { action: "Lead Created", date: "2025-02-01", note: "Website inquiry" },
      { action: "Contacted", date: "2025-02-03", note: "Discussed plots" },
      { action: "Visit Scheduled", date: "2025-02-06", note: "Booked visit" },
      { action: "Visit Completed", date: "2025-02-08", note: "Visited site" },
      { action: "Lost", date: "2025-02-14", note: "Chose competitor" },
    ],
  },
  {
    id: 6,
    name: "Rohit Sharma",
    phone: "9600334455",
    email: "rohit@email.com",
    property: "Metro Heights 2BHK",
    propertyId: 3,
    budget: 3200000,
    location: "Noida",
    stage: "Contacted",
    source: "Chatbot",
    assignedTo: "Vikram Singh",
    notes: [
      {
        text: "First-time buyer, needs guidance on EMI and registration",
        date: "2025-02-15",
      },
    ],
    followUpDate: "2025-02-19",
    visitDate: null,
    createdAt: "2025-02-13",
    updatedAt: "2025-02-15",
    timeline: [
      { action: "Lead Created", date: "2025-02-13", note: "Chatbot inquiry" },
      {
        action: "Contacted",
        date: "2025-02-15",
        note: "Explained EMI options",
      },
    ],
  },
];

/* ─── VISITS ─────────────────────────────────────────────────────────────────── */
export const MOCK_VISITS = [
  {
    id: 1,
    leadId: 2,
    leadName: "Sneha Gupta",
    property: "Green Valley Villas",
    date: "2025-02-18",
    time: "11:00 AM",
    status: "Scheduled",
    assignedTo: "Priya Sharma",
  },
  {
    id: 2,
    leadId: 3,
    leadName: "Arjun Patel",
    property: "Metro Heights 2BHK",
    date: "2025-02-12",
    time: "03:00 PM",
    status: "Completed",
    assignedTo: "Vikram Singh",
  },
  {
    id: 3,
    leadId: 4,
    leadName: "Meera Shah",
    property: "Skyline Apartments Block A",
    date: "2025-02-05",
    time: "10:00 AM",
    status: "Interested",
    assignedTo: "Priya Sharma",
  },
  {
    id: 4,
    leadId: 5,
    leadName: "Kavya Nair",
    property: "Central Park Plots",
    date: "2025-02-08",
    time: "02:00 PM",
    status: "Not Interested",
    assignedTo: null,
  },
  {
    id: 5,
    leadId: 1,
    leadName: "Rahul Verma",
    property: "Skyline Apartments Block A",
    date: "2025-02-22",
    time: "11:30 AM",
    status: "Scheduled",
    assignedTo: "Vikram Singh",
  },
];

/* ─── TASKS / FOLLOW-UPS ─────────────────────────────────────────────────────── */
export const MOCK_TASKS = [
  {
    id: 1,
    leadId: 1,
    leadName: "Rahul Verma",
    type: "Call",
    date: "2025-02-20",
    note: "Confirm site visit interest",
    done: false,
  },
  {
    id: 2,
    leadId: 3,
    leadName: "Arjun Patel",
    type: "Meeting",
    date: "2025-02-16",
    note: "Discuss final discount & booking",
    done: false,
  },
  {
    id: 3,
    leadId: 6,
    leadName: "Rohit Sharma",
    type: "Call",
    date: "2025-02-19",
    note: "Share EMI calculator document",
    done: false,
  },
  {
    id: 4,
    leadId: 2,
    leadName: "Sneha Gupta",
    type: "Visit",
    date: "2025-02-18",
    note: "Site visit at Green Valley Villas",
    done: false,
  },
  {
    id: 5,
    leadId: 4,
    leadName: "Meera Shah",
    type: "Call",
    date: "2025-02-10",
    note: "Post-booking documentation",
    done: true,
  },
];

/* ─── DEALERS (for super admin) ──────────────────────────────────────────────── */
export const MOCK_DEALERS = [
  {
    id: 1,
    name: "ABC Properties",
    slug: "abc-properties",
    owner: "Raj Sharma",
    email: "raj@abc.com",
    city: "Noida",
    plan: "PRO",
    status: "ACTIVE",
    leads: 342,
    visits: 182,
    closed: 28,
    joinedAt: "2024-01-10",
  },
  {
    id: 2,
    name: "Elite Realty",
    slug: "elite-realty",
    owner: "Priya Mehta",
    email: "priya@elite.com",
    city: "Mumbai",
    plan: "BASIC",
    status: "ACTIVE",
    leads: 189,
    visits: 94,
    closed: 12,
    joinedAt: "2024-02-14",
  },
  {
    id: 3,
    name: "Dream Homes",
    slug: "dream-homes",
    owner: "Arjun Singh",
    email: "arjun@dream.com",
    city: "Delhi",
    plan: "ENTERPRISE",
    status: "ACTIVE",
    leads: 621,
    visits: 310,
    closed: 71,
    joinedAt: "2023-11-05",
  },
  {
    id: 4,
    name: "Green Spaces",
    slug: "green-spaces",
    owner: "Neha Kapoor",
    email: "neha@green.com",
    city: "Pune",
    plan: "PRO",
    status: "INACTIVE",
    leads: 45,
    visits: 21,
    closed: 2,
    joinedAt: "2024-03-22",
  },
  {
    id: 5,
    name: "Urban Nests",
    slug: "urban-nests",
    owner: "Vikram Patel",
    email: "vikram@urban.com",
    city: "Bangalore",
    plan: "BASIC",
    status: "ACTIVE",
    leads: 278,
    visits: 134,
    closed: 19,
    joinedAt: "2024-01-30",
  },
  {
    id: 6,
    name: "Royal Estates",
    slug: "royal-estates",
    owner: "Ananya Roy",
    email: "ananya@royal.com",
    city: "Hyderabad",
    plan: "ENTERPRISE",
    status: "ACTIVE",
    leads: 510,
    visits: 260,
    closed: 58,
    joinedAt: "2023-09-18",
  },
];

export const SYSTEM_STATS = {
  totalDealers: 6,
  activeDealers: 5,
  totalLeads: 1985,
  totalVisits: 1001,
  monthlyRevenue: 284000,
  growth: 18.4,
};
